web/router.ex
defmodule Anvers.Router do
  use Anvers.Web, :router

  use Addict.RoutesHelper

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Anvers do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/contact", PageController, :contact
    get "/about", PageController, :about

    get "/posts", PostController, :index
    get "/posts/:id", PostController, :show
  end

  scope "/admin", Anvers do
    pipe_through :browser

    get "/", AdminController, :index
    get "/posts", AdminController, :index_post
    get "/posts/:id/edit", AdminController, :edit_post
    get "/posts/new", AdminController, :new_post
    post "/posts", AdminController, :create_post
    patch "/posts/:id", AdminController, :update_post
    put "/posts/:id", AdminController, :update_post
    delete "/posts/:id", AdminController, :delete_post

    get "/login", Admin.UserController, :login
    post "/login", Admin.UserController, :do_login
    post "/logout", Admin.UserController, :logout
    get "/register", Admin.UserController, :register
    post "/register", Admin.UserController, :do_register
  end


  # Other scopes may use custom stacks.
  # scope "/api", Anvers do
  #   pipe_through :api
  # end
end

web/models/post.ex
defmodule Anvers.Post do
  use Anvers.Web, :model

  schema "posts" do
    field :title, :string
    field :body, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
  end
end

web/controllers/post_controller.ex
defmodule Anvers.PostController do
  use Anvers.Web, :controller

  alias Anvers.Post

  def index(conn, _params) do
    posts = Repo.all(Post)
    render(conn, "index.html", posts: posts)
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    render(conn, "show.html", post: post)
  end

end

web/views/post_view.ex
defmodule Anvers.PostView do
  use Anvers.Web, :view
end

web/templates/post/edit.html.eex
<h2>Edit post</h2>
<div class="row">

  <div class="col-md-9">
    <%= form_for @changeset, post_path(@conn, :update, @post), [id: "post-form"],  fn f -> %>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

      <div class="form-group">
        <%= label f, :title, class: "control-label" %>
        <%= text_input f, :title, class: "form-control" %>
        <%= error_tag f, :title %>
      </div>

      <div class="form-group">
        <%= label f, :body, class: "control-label" %>
        <%= textarea f, :body, class: "form-control" %>
        <%= error_tag f, :body %>
      </div>

    <% end %>
  </div>

  <div class="col-md-3">
    <div class="box">
      <span class="box-title">Actions</span>
      <button data-submit-target="post-form" class="btn btn-primary btn-xs anvers-submit-target">Save</button>
      <a href="<%= post_path(@conn, :index) %>" class="btn btn-warning btn-xs">Cancel</a>
      <%= link "Delete", to: post_path(@conn, :delete, @post), method: :delete, data: [confirm: "Really?"], class: "btn btn-danger btn-xs", form: [class: "form-inline"] %>
    </div>
  </div>

</div>

web/templates/post/edit_scripts.html.eex
<%= render  "simplemde_js.html", assigns %>

web/templates/post/edit_styles.html.eex
<%= render  "simplemde_css.html", assigns %>

web/templates/post/index.html.eex
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

  <%= for post <- @posts do %>
    <div class="post-preview">
      <a href="<%= post_path(@conn, :show, post) %>">
        <h2 class="post-title">
          <%= post.title %>
        </h2>
        <h3 class="post-subtitle">
          SUBTITLE?
        </h3>
      </a>
      <p class="post-meta">Posted by <a href="#">Unknown</p>
    </div>
    <hr>
  <% end %>

  </div>
</div>

web/templates/post/new.html.eex
<h2>Create post</h2>
<div class="row">
          <%= form_for @changeset, post_path(@conn, :create), fn f -> %>
          <div class="col-md-9">
            <%= if @changeset.action do %>
              <div class="alert alert-danger">
                <p>Oops, something went wrong! Please check the errors below.</p>
              </div>
            <% end %>

            <div class="form-group">
              <%= label f, :title, class: "control-label" %>
              <%= text_input f, :title, class: "form-control" %>
              <%= error_tag f, :title %>
            </div>

            <div class="form-group">
              <%= label f, :body, class: "control-label" %>
              <%= textarea f, :body, class: "form-control" %>
              <%= error_tag f, :body %>
            </div>


          </div>

          <div class="col-md-3">
            <div class="box">
              <span class="box-title">Actions</span>
              <%= submit "Save", class: "btn btn-primary btn-xs" %>
              <a href="<%= post_path(@conn, :index) %>" class="btn btn-warning btn-xs">Cancel</a>
            </div>
          </div>
          <% end %>
</div>

web/templates/post/new_scripts.html.eex
<%= render  "simplemde_js.html", assigns %>

web/templates/post/new_styles.html.eex
<%= render  "simplemde_css.html", assigns %>

web/templates/post/show.html.eex
<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <a href="<%= admin_path(@conn, :edit_post, @post) %>"><i class="icon-cog text-red fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>
        <%= raw(Earmark.to_html(@post.body)) %>
      </div>
    </div>
  </div>
</article>
<hr>

web/templates/post/show_header.html.eex
<header class="intro-header" style="background-image: url('<%= static_path(@conn, "/images/post-bg.jpg") %>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1><%= @post.title %></h1>
                    <hr class="small">
                    <span class="subheading">Some blog subtitle</span>
                </div>
            </div>
        </div>
    </div>
</header>

web/templates/post/simplemde_css.html.eex
<link rel="stylesheet" href="<%= static_path(@conn, "/vendor/simplemde/css/simplemde.min.css") %>">

web/templates/post/simplemde_js.html.eex
<script src="<%= static_path(@conn, "/vendor/simplemde/js/simplemde.min.js") %>"></script>


<script>
  (function() {
    var simplemde = new SimpleMDE({
        autofocus: true,
        element: document.getElementById("post_body"),
        placeholder: "Type here..."
    });
  })();
</script>